### PR TITLE
Update (some) system prompts to be accurate as of 2023-11-03

### PR DESCRIPTION
**Pull request by michaelskyba**
### Advanced Data Analysis
- Knowledge cutoff updated
- Line breaks updated

### DALL-E
- Knowledge cutoff updated
- General wording changes
- New policy surrounding copyright added

### Vision
- Knowledge cutoff updated
- Most blank lines removed

### Android
- Knowledge cutoff updated
- Note about LaTeX added

### Base
- Knowledge cutoff updated

### Misc notes
- The knowledge cutoffs for Browse with Bing and Plugins were not updated, at least not in the system prompt
- I don't have access to iOS (CBA to set my browser's User-Agent to iOS) or All Tools. The former probably also has the same mobile update, but the latter probably hasn't changed since spdustin's last commit
- I didn't check for an update on the mobile Voice conversation mode
- I added newlines to end of markdown files that didn't have them, for consistency. Browse with Bing and All Tools had them previously.

### CODE REVIEW

**Comment by MiraScarfiotti-nbcuni** [comment]
the ADA prompt fixes it for me, thank you!

**Comment by michaelskyba** [comment]
Fixes what? The ChatGPT servers use these automatically

**Comment by spdustin** [comment]
> ### Advanced Data Analysis
> * Knowledge cutoff updated
> * Line breaks updated
> ***<snip>***

These are the prompts you got in those specific modes, and not just extracted from the "All Tools" mode?

**Comment by michaelskyba** [comment]
> > ### Advanced Data Analysis
> > 
> > * Knowledge cutoff updated
> > * Line breaks updated
> >   _**<snip>**_
> 
> These are the prompts you got in those specific modes, and not just extracted from the "All Tools" mode?

Yes, I got all of these from those specific modes; I didn't take anything from the All Tools mode. The dall-e.md prompt, for example, is inconsistent with what looks like the related portion in all_tools.md.

**Review by spdustin — APPROVED** [review]
LGTM, though I'm on the fence about whitespace changes. I can't decide between accuracy or ease of browsing here, and whitespace doesn't impact how prompts are attended to. I'm merging anyway, since I don't think there's a perfect answer here. Thanks!

**Comment by michaelskyba** [comment]
> LGTM, though I'm on the fence about whitespace changes. I can't decide between accuracy or ease of browsing here, and whitespace doesn't impact how prompts are attended to. I'm merging anyway, since I don't think there's a perfect answer here. Thanks!

Do you think it would make sense to maintain human-parseable markdown versions in addition to the raw prompts? dall-e.md is basically impossible to follow as it is now, for example.

**Comment by spdustin** [comment]
I wrote a GitHub action I'm using on a private repo to clean up Markdown, so I could use that.

One issue is that, since extra whitespace isn't that meaningful to GPT, the way it responds to a prompt that emits the system message isn't deterministic, even when using more explicit instructions to return the text verbatim.

DALL•E is harder to follow, for sure, but is also a special case, since it's using the same middleware as plugins to pass messages back to the backend. There are other differences between plugins, `browser`, and `python` and their message-passing interface that make me think (a) different teams built them and (b) the technical debt they've racked up as a result will be paid off soon-ish.

So, as ever, I remain on the fence. 😆 I'll be watching to see what happens after the DevDay launch (🤞) of Gizmos.

**Pull request merged**
